server:
  port: 17002
spring:
  profiles:
    active: "dev"
    group:
      "dev": "dev,api"
# Eureka配置
eureka:
  instance:
    # Eureka服务端的实例名字
    hostname: eureka17002.com
  client:
    # 表示是否向 Eureka 注册中心注册自己(这个模块本身是服务器,所以不需要)
    register-with-eureka: false
    # fetch-registry如果为false,则表示自己为注册中心,客户端的化为 ture
    fetch-registry: false
    # Eureka监控页面~
    service-url:
      # 单机
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # 集群
      defaultZone: http://eureka17001.com:17001/eureka/,http://eureka17003.com:17003/eureka/
